apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: slack-webhook-url
  namespace: monitoring
spec:
  encryptedData:
    url: AgBc04YDdko32ldznZ/LCHVStJMXmi7k7xn5Mt/qnVMGqIDzwPSYp5KXmQti0Q/eiIYolTOlfVzQv2LFFWp5eCzXQ7RjrWbF9gVq1vcISPihhus8zSzgt44jlZfiIcNbDEKvByVzEl6vBGui1ur/T4JMzIcOzbbUVU7UiE1YTsjHjqF06gIpOmMUC+G9wm9Vkx8ms6Ob5sjFmJwczC4JRobucBqUCy/5x0hL0IYK0zHrkKMv/VLrj88qThxLL+Rqil00kuyvAELZFUdEs7xCu0Oy/c4Fv6/CiTKNjavlPv/YWlEloqFKD6RFVEs5gV+kdJgR3yEpvRSJNZCKLVQXdSXEgbLxi405DJX0IV4hOHtd46G1sDFuE6hkYI5rMzM9jUBC9OGHryqJBbIpM9nInAM3F9cLF8D2CoVrt+lVUiwj4gZ54m3vT5AVJBkMqsRpn4YEN2R/gTSfhOeXyST5irHDxWz4IJusYpW6B/MQlQn0fZUQCuUkv6I8vyniM8+VcuuY+FzsSoVGpCn8byJigTtkOZ4XHXmsBlarEx0z1c3QmHAR+s5/FOdEF61Ax3BCmBZWvwZd0zdyPwRcJsYqbOUAA5aG7JGX3+p9D3ppe5HIfF0N2ufsNKrJ/HEuU/6AaANMaMdLug5xjibl68NSUh/qVVVDg7UEEuUx6akuSqhYw0oz1KgkRpdDnTwJu3JZKrZKIKDSXq4JannqP8wuoKW2UhpCNwKUa/21A1TGpEvSuLUdCaIdiYAhYS8/DTbPM30bi4fJ4Gf3ROntdn5cbCpCpto1K/4gxnBFuZKFuLSxsj8Y
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: slack-webhook-url
      namespace: monitoring
    type: Opaque

