apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: slack-webhook-url
  namespace: monitoring
data:
  url: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDA0TDlEODc5NDIvQjA1NUNHWUFWOVMvTVJoQ1k1NXQ4eGV2VUF3SUdJRjA2S0YyCg==
  