apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopping-website
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mmelmesary/DevOps-Project.git
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: app-system
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true