apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secret
spec:
project: default
source:
  repoURL: 'https://bitnami-labs.github.io/sealed-secrets/'
  targetRevision: 2.8.2
  chart: sealed-secrets
destination:
  server: 'https://kubernetes.default.svc'
  namespace: sealed-secret
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
