apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mmelmesary/DevOps-Project.git
    targetRevision: HEAD
    path: ArgoCD/app-of-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  syncPolicy:
    syncOptions:
    - createNamespace=true
    automated:
      selfHeal: true
      prune: true